#!/bin/bash
# Interactive setup script for Church Video Streaming

echo "=== Church Video Streaming Setup ==="
echo ""

# --- VIDEO DEVICE SELECTION ---
echo "Detecting video devices..."
echo ""

# Get video devices (first /dev/videoX for each device)
mapfile -t video_devices < <(v4l2-ctl --list-devices 2>/dev/null | grep -E "^\s+/dev/video[0-9]+$" | awk 'NR % 2 == 1' | tr -d '\t')
mapfile -t video_names < <(v4l2-ctl --list-devices 2>/dev/null | grep -v "^\s" | sed 's/(.*//')

if [ ${#video_devices[@]} -eq 0 ]; then
    echo "No video devices found. Is v4l-utils installed?"
    exit 1
fi

echo "SELECT VIDEO DEVICE:"
echo "--------------------"
for i in "${!video_devices[@]}"; do
    echo "  $((i+1))) ${video_devices[$i]} - ${video_names[$i]}"
done
echo ""
read -p "Enter number [1-${#video_devices[@]}]: " video_choice

if [[ "$video_choice" -lt 1 || "$video_choice" -gt ${#video_devices[@]} ]]; then
    echo "Invalid selection"
    exit 1
fi
selected_video="${video_devices[$((video_choice-1))]}"
echo "Selected: $selected_video"
echo ""

# --- AUDIO DEVICE SELECTION ---
echo "Detecting audio devices..."
echo ""

# Get audio cards
mapfile -t audio_cards < <(arecord -l 2>/dev/null | grep "^card" | sed 's/:.*//' | awk '{print $2}')
mapfile -t audio_names < <(arecord -l 2>/dev/null | grep "^card" | sed 's/^[^:]*\[//' | sed 's/\].*$//')

if [ ${#audio_cards[@]} -eq 0 ]; then
    echo "No audio devices found. Is alsa-utils installed?"
    exit 1
fi

echo "SELECT AUDIO DEVICE:"
echo "--------------------"
for i in "${!audio_cards[@]}"; do
    echo "  $((i+1))) hw:${audio_cards[$i]},0 - ${audio_names[$i]}"
done
echo ""
read -p "Enter number [1-${#audio_cards[@]}]: " audio_choice

if [[ "$audio_choice" -lt 1 || "$audio_choice" -gt ${#audio_cards[@]} ]]; then
    echo "Invalid selection"
    exit 1
fi
selected_audio="hw:${audio_cards[$((audio_choice-1))]},0"
echo "Selected: $selected_audio"
echo ""

# --- TARGET IP ---
echo "TARGET IP (OBS Machine):"
echo "------------------------"

# Try to find devices on local network
echo "  1) Enter manually"
echo "  2) This machine (localhost/127.0.0.1)"

# Get local IP to suggest common alternatives
local_ip=$(hostname -I | awk '{print $1}')
if [ -n "$local_ip" ]; then
    network_prefix=$(echo "$local_ip" | sed 's/\.[0-9]*$/./')
    echo "  3) Scan network ${network_prefix}0/24 (slow)"
fi
echo ""
read -p "Enter choice: " ip_choice

case "$ip_choice" in
    1)
        read -p "Enter target IP address: " selected_ip
        ;;
    2)
        selected_ip="127.0.0.1"
        ;;
    3)
        echo "Scanning network (this may take 10-20 seconds)..."
        echo "Active hosts:"
        nmap -sn "${network_prefix}0/24" 2>/dev/null | grep "Nmap scan" | sed 's/Nmap scan report for /  /'
        echo ""
        read -p "Enter target IP address: " selected_ip
        ;;
    *)
        echo "Invalid selection"
        exit 1
        ;;
esac
echo "Selected: $selected_ip"
echo ""

# --- SAVE CONFIG ---
echo "# Church Video Streaming Config" > .config.mk
echo "# Generated by 'make setup' on $(date)" >> .config.mk
echo "" >> .config.mk
echo "VIDEO_DEV = $selected_video" >> .config.mk
echo "AUDIO_DEV = $selected_audio" >> .config.mk
echo "TARGET_IP = $selected_ip" >> .config.mk

echo "=== Configuration saved to .config.mk ==="
echo ""
cat .config.mk
echo ""
echo "Next steps:"
echo "  make test-video   - Test video capture"
echo "  make test-audio   - Test audio levels"
echo "  make stream-udp   - Start streaming to OBS"
